# ruff: noqa: F401
# pyright: reportUnusedImport=false

from dataclasses import dataclass
from typing import List, Protocol

import i13c.syntax.tree.function as function
import i13c.syntax.tree.literals as literals
import i13c.syntax.tree.snippet as snippet
import i13c.syntax.tree.types as types
from i13c.syntax.tree.core import Path


class Visitor(Protocol):
    def on_program(self, program: Program, path: Path) -> None: ...

    # snippet related
    def on_snippet(self, snippet: snippet.Snippet, path: Path) -> None: ...
    def on_signature(self, signature: snippet.Signature, path: Path) -> None: ...
    def on_slot(self, slot: snippet.Slot, path: Path) -> None: ...
    def on_bind(self, bind: snippet.Bind, path: Path) -> None: ...
    def on_label(self, label: snippet.Label, path: Path) -> None: ...
    def on_instruction(self, instruction: snippet.Instruction, path: Path) -> None: ...
    def on_immediate(self, immediate: snippet.Immediate, path: Path) -> None: ...
    def on_register(self, register: snippet.Register, path: Path) -> None: ...
    def on_reference(self, reference: snippet.Reference, path: Path) -> None: ...

    # function related
    def on_function(self, function: function.Function, path: Path) -> None: ...
    def on_statement(self, statement: function.Statement, path: Path) -> None: ...
    def on_literal(self, literal: function.Literal, path: Path) -> None: ...
    def on_expression(self, expression: function.Expression, path: Path) -> None: ...
    def on_operand(self, operand: snippet.Operand, path: Path) -> None: ...
    def on_parameter(self, parameter: function.Parameter, path: Path) -> None: ...

    # types related
    def on_type(self, type: types.Type, path: Path) -> None: ...
    def on_range(self, range: types.Range, path: Path) -> None: ...


@dataclass(kw_only=True, eq=False)
class Program:
    functions: List[function.Function]
    snippets: List[snippet.Snippet]

    def accept(self, visitor: Visitor, path: Path) -> None:
        visitor.on_program(self, path)

        with path.push(self) as node:
            for entry in self.snippets:
                entry.accept(visitor, node)

            for entry in self.functions:
                entry.accept(visitor, node)
